---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hostkenyaco/Marsha-Creatives-Business-Management-System/
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
